// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwzubwiZYvi0qpeDGYlTbA9EhXMWYQXjM',
    appId: '1:481823508776:web:46803f6543d5dfca0d281d',
    messagingSenderId: '481823508776',
    projectId: 'near-by-store-2eecc',
    authDomain: 'near-by-store-2eecc.firebaseapp.com',
    storageBucket: 'near-by-store-2eecc.appspot.com',
    measurementId: 'G-HD2N3SY8N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7WEG9KSnpPr0Cc1cvAekpVGKHyX-_g84',
    appId: '1:481823508776:android:bc1525c0433a817b0d281d',
    messagingSenderId: '481823508776',
    projectId: 'near-by-store-2eecc',
    storageBucket: 'near-by-store-2eecc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBKQwPwtQgJ1htjXiIrfQVbdBnnIkmNqs',
    appId: '1:481823508776:ios:2839a685e497bc2e0d281d',
    messagingSenderId: '481823508776',
    projectId: 'near-by-store-2eecc',
    storageBucket: 'near-by-store-2eecc.appspot.com',
    iosBundleId: 'com.example.nearByStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBKQwPwtQgJ1htjXiIrfQVbdBnnIkmNqs',
    appId: '1:481823508776:ios:139a8d58aa4a2e240d281d',
    messagingSenderId: '481823508776',
    projectId: 'near-by-store-2eecc',
    storageBucket: 'near-by-store-2eecc.appspot.com',
    iosBundleId: 'com.example.nearByStore.RunnerTests',
  );
}
